IDIR =../include
CC=gcc
CFLAGS=-ggdb -I$(IDIR) -Wall
ODIR=obj
LDIR =../lib

LIBS=-lpthread

_DEPS = # proxy.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = proxy.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

$(ODIR)/%.o: %.c $(DEPS)
	mkdir -p $(ODIR)
	$(CC) -c -o $@ $< $(CFLAGS)

proxy: $(OBJ)
	gcc -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f proxy $(ODIR)/*.o *~ core $(INCDIR)/*~

